--liquibase formatted sql
--changeset rafal:locations_table runOnChange:false context:INITIAL_SYNC labels:INITIAL_SYNC
--comment Initial changeset for locations_table
  CREATE TABLE "RAFAL"."LOCATIONS" 
   (	"LOCATION_ID" NUMBER(4,0),
	"STREET_ADDRESS" VARCHAR2(40 CHAR),
	"POSTAL_CODE" VARCHAR2(12 CHAR),
	"CITY" VARCHAR2(30 CHAR) CONSTRAINT "LOC_CITY_NN" NOT NULL ENABLE,
	"STATE_PROVINCE" VARCHAR2(25 CHAR),
	"COUNTRY_ID" CHAR(2 CHAR),
	CONSTRAINT "LOC_ID_PK" PRIMARY KEY ("LOCATION_ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE,
	CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_ID")
	 REFERENCES "RAFAL"."COUNTRIES" ("COUNTRY_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"
