####################
#### ATTENTION ####
####################
###BEFORE RUNNING THIS SCRIPT PROVIDE BACKUP OF YOUR /DATABASE/ FOLDER and make some test runs on it first!
####################
# Global variables
$space = ' '
$new_line = "`n"
# `n means - add enter
#username on all changesets
$username  = "rafal"
$context   = "context:INITIAL_SYNC"
$labels    = "labels:INITIAL_SYNC"
$endDelimiter = "endDelimier:\n/" #used for replaceable changesets



###### SET REPLACEABLE OBJECTS ####
# Execute this script in /database/ folder where are folders like package_spec, type_spec, table etc
# it takes path to your objects and assigns it to a variable (path to folders with replaceable objects like package_spec, triggers, views)
# folder namings are exact the same like those auto generated by SQLcl liquibase generate-schema --split command
# If folder does not exists -script will skip it
if (Test-Path -Path ".\package_spec") {
    $package_spec = (Get-ChildItem -Path ".\package_spec").FullName
} else {
    $package_spec = @()
}

if (Test-Path -Path ".\package_body") {
    $package_body = (Get-ChildItem -Path ".\package_body").FullName
} else {
    $package_body = @()
}

if (Test-Path -Path ".\procedure") {
    $procedure = (Get-ChildItem -Path ".\procedure").FullName
} else {
    $procedure = @()
}

if (Test-Path -Path ".\function") {
    $function = (Get-ChildItem -Path ".\function").FullName
} else {
    $function = @()
}

if (Test-Path -Path ".\view") {
    $view = (Get-ChildItem -Path ".\view").FullName
} else {
    $view = @()
}

if (Test-Path -Path ".\materialized_view") {
    $materialized_view = (Get-ChildItem -Path ".\materialized_view").FullName
} else {
    $materialized_view = @()
}

if (Test-Path -Path ".\trigger") {
    $trigger = (Get-ChildItem -Path ".\trigger").FullName
} else {
    $trigger = @()
}

if (Test-Path -Path ".\synonym") {
    $synonym = (Get-ChildItem -Path ".\synonym").FullName
} else {
    $synonym = @()
}

if (Test-Path -Path ".\type_spec") {
    $type_spec = (Get-ChildItem -Path ".\type_spec").FullName
} else {
    $type_spec = @()
}

if (Test-Path -Path ".\type_body") {
    $type_body = (Get-ChildItem -Path ".\type_body").FullName
} else {
    $type_body = @()
}

if (Test-Path -Path ".\synonym") {
    $synonym = (Get-ChildItem -Path ".\synonym").FullName
} else {
    $synonym = @()
}

# merge all replaceable objects into one
$replaceable = $package_spec + $package_body + $procedure +$function + $view + $trigger + $synonym + $type_spec + $type_body + $materialized_view + $synonym  # ADD OTHERS IF YOU HAVE MORE FOLDERS

###### SET NON - REPLACEABLE OBJECTS ####
#path to folders with NON - replaceable objects like table or sequences
if (Test-Path -Path ".\table") {
    $table = (Get-ChildItem -Path ".\table").FullName
} else {
    $table = @()
}

if (Test-Path -Path ".\sequence") {
    $sequence = (Get-ChildItem -Path ".\sequence").FullName
} else {
    $sequence = @()
}

if (Test-Path -Path ".\index") {
    $index = (Get-ChildItem -Path ".\index").FullName
} else {
    $index = @()
}

if (Test-Path -Path ".\ref_constraint") {
    $ref_constraint = (Get-ChildItem -Path ".\ref_constraint").FullName
} else {
    $ref_constraint = @()
}


if (Test-Path -Path ".\db_link") {
    $db_link = (Get-ChildItem -Path ".\db_link").FullName
} else {
    $db_link = @()
}

if (Test-Path -Path ".\job") {
    $job = (Get-ChildItem -Path ".\job").FullName
} else {
    $job = @()
}

if (Test-Path -Path ".\comment") {
    $comment = (Get-ChildItem -Path ".\comment").FullName
} else {
    $comment = @()
}

# merge all NON-replaceable objects into one
$non_replaceable = $table + $sequence + $index + $ref_constraint + $db_link + $job +$comment # ADD OTHERS IF YOU HAVE MORE FOLDERS
#set all objects
$all = $replaceable + $non_replaceable;

###################################################
### CREATE CHANGESETS FOR REPLACEABLE  OBJECTS ####
###################################################
#do for each file / LOOP
ForEach ($sqlfile in $all) {
    # get original file content -raw is important to not lose your file formatting e.g. spaces and new lines
    $original_content = Get-content -Raw $sqlfile
    #take only filename without extension / we will use it later as changeset ID
    $filename = [System.IO.Path]::GetFileNameWithoutExtension("$sqlfile")

    If ($original_content -imatch "--liquibase formatted sql") 
    {
        echo "File already has changeset - nothing to add!"
        $filename

    }
        else #add changesets
    {
        # Set appropriate runOnChange parameter
        switch ($sqlfile) {
            {$_ -in $replaceable} {$runOnChange = "runOnChange:true endDelimiter:\n/" + $space}
            {$_ -in $non_replaceable} {$runOnChange = "runOnChange:false" + $space}     
        }
        #create liquibase syntax
        $liquibase      = "--liquibase formatted sql" + $new_line
        $changeset      = "--changeset" + $space
        $changeset_id   = $filename + $space
        $comment        = "--comment Initial changeset for $filename" + "`n"

        # optional fake rollback. When running "liquibase rollback" command it will not touch your DB objects, but only remove rows from DATABASECHANGELOG tracking table.
        # when creating new changesets always add working rollback to your change and test it with "liquibase updateTestingRollback" command
        $rollback       = "--rollback SELECT 1 FROM DUAL"  + "`n"    

        #add liquibase's changeset parameters on top of modified file
        $content_modified = $liquibase + $changeset +$username + ":"  + $changeset_id + $runOnChange + $context + $space + $labels + $new_line + $comment + $original_content
        #+ $rollback
        #set new content of modified file
        $content_modified | Set-Content $sqlfile
    }
    }

